### ISSUE TITLE
opening bash and returning to app loses focus

### ISSUE THREAD

**Issue by sadeqAlbana** [gansm/finalcut#36]
I've been using this library for a while now and I'm really impressed with it.
I have and option in my ListView to open the bash from the app,  when the user clicks the bash option the following function is called

`void MainDialog::startBash()
{
    system("cd; clear; reset; sudo bash");
}`
now when when I type "exit" I lose focus and can't do any navigation.
is there a way to restore focus to the app after executing these commands ?.

**Comment by gansm** [comment]
Hello sadeqAlbana, 
nice that you like my widget toolkit. Unfortunately, your problem is a bit too complex to manage it with a small patch. Let me explain what the problem is.

The system call via `system(…)` changes the terminal settings that are required for FINAL CUT. After returning from the shell, the program is in a changed environment. This causes, for example, that keystrokes are no longer detected, the terminal is no longer in the required raw mode, the alternate screen was left and the color palette was reset. The mouse support in the terminal was also deactivated by the system call. Also, the cursor position of the virtual terminal no longer corresponds to the current position.

I have here a small dirty hack which corrects most settings after the system call.

```cpp
#include <final/final.h>
 
using namespace finalcut;
 
class MyDialog : public FDialog
{
  public:
    explicit MyDialog (FWidget* parent = nullptr)
      : FDialog(parent)
    {
      setGeometry (FPoint(25, 5), FSize(35, 6));
      setText("Test");
      btn1.setGeometry (FPoint(3, 2), FSize(10, 1));
      btn2.setGeometry (FPoint(20, 2), FSize(10, 1));
 
      btn1.addCallback
      (
        "clicked",
        F_METHOD_CALLBACK (this, &MyDialog::cb_shell),
        nullptr
      );
 
      btn2.addCallback
      (
        "clicked",
        F_METHOD_CALLBACK (this, &FApplication::cb_exitApp),
        nullptr
      );
    }
 
  private:
    void cb_shell (finalcut::FWidget*, FDataPtr)
    {
      // Restore the saved termios settings
      FTermios::restoreTTYsettings();

      // Disable the xterm mouse
      FTermXTerminal::setMouseSupport(false);

      // Show the terminal cursor
      FTerm::cursorsVisibility(true);

      // Execute shell command   
      system("cd; clear; reset; sudo bash");

      // Switch to the alternate screen
      if ( FTerm::hasAlternateScreen() )
      {
        FTerm::putstring (TCAP(fc::t_enter_ca_mode));
        std::fflush(stdout);
      }

      // Hide the terminal cursor
      FTerm::cursorsVisibility(false);

      // Reactivating the xterm mouse
      FTermXTerminal::setMouseSupport(true);

      // Redefine the FINAL CUT color palette
      if ( getMaxColor() >= 16 )
        FColorPalette::set16ColorPalette (FTerm::setPalette);
      else  // 8 colors
        FColorPalette::set8ColorPalette (FTerm::setPalette);

      // Turn off hardware echo
      FTermios::unsetHardwareEcho();
 
      // Switch to the raw mode
      FTermios::setRawMode();
      FTermios::setCaptureSendCharacters();

      int x = getPrintCursor().getX();
      int y = getPrintCursor().getY();
      FTerm::moveCursor (-1, -1, x, y);
      auto app = FApplication::getApplicationObject();
      app->redraw();
    }
 
    // Data Members
    FButton btn1{"&Shell", this};
    FButton btn2{"&Quit", this};
};
 
int main (int argc, char* argv[])
{
  FApplication app(argc, argv);
  MyDialog dialog(&app);
  app.setMainWidget(&dialog);
  dialog.show();
  return app.exec();
}
```

But there is only one reasonable solution to your problem, and that is to implement a widget with a terminal-emulation. This is one of the features I have planned for the remote future. The complexity of the parser is very high so that the implementation might take some time. When it's finished, you will be able to run a Unix shell in a FINAL CUT window.

A parser for DEC’s ANSI-compatible video terminals:
https://vt100.net/emu/dec_ansi_parser

**Comment by sadeqAlbana** [comment]
thanks, this really did the job for me perfectly.
terminal emulation seems like a nice idea, and that's the first thing that came to my mind when I needed to open the terminal from the app.
implementing is would require a lot of effort, but I can see it as an important feature, since I guess some people will use this framework to build a sysmenu for some sort of a linux server distribution.
and once again, I'm very grateful for for your help.
