### ISSUE TITLE
mouse doesn't work

### ISSUE THREAD

**Issue by okbob** [gansm/finalcut#38]
After today update from git the mouse is not initialized and is not active. Tested on Fedora Core 31.

**Comment by gansm** [comment]
Thanks for your test report.

I have found the reason for this:
    gcc has optimized out the global static FStartOptions object. Therefore, the default values couldn't set at startup.

So for now, you can use
```bash
./configure --prefix=/usr CXXFLAGS="-O0"
```
as a workaround.

I have already fixed the code locally. But I can't publish it yet, because I'm currently working on a significant change in the core.

**Comment by okbob** [comment]
Dne po 16. 9. 2019 15:51 uživatel Markus Gans <notifications@github.com>
napsal:

> Thanks for your test report.
>
> I have found the reason for this:
>     gcc has optimized out the global static FStartOptions object.
> Therefore, the default values couldn't set at startup.
>
> So for now, you can use
>
> ./configure --prefix=/usr CXXFLAGS="-O0"
>
> as a workaround.
>
> I have already fixed the code locally. But I can't publish it yet, because
> I'm currently working on a significant change in the core.
>

it is working

Pavel

**Comment by gansm** [comment]
In the meantime, I have committed a version (8c67f64) with this fix.

**Comment by okbob** [comment]
I can confirm. It is fixed, thank you
