### ISSUE TITLE
Has anyone tested with VC 17 /19 on windows?

### ISSUE THREAD

**Issue by ghost** [gansm/finalcut#60]
Thanks

**Comment by gansm** [comment]
Now that the questioner's account has been deleted and there is no further activity here, I am closing this issue.

**Comment by Ryder17z** [comment]
> Thank you for your interest in FINAL CUT. I don't own Microsoft Visual Studio myself, and so I can't test it. But I could imagine that cross-compiling for a POSIX environment could be possible with this IDE.
> 
> FAQ: [Are Windows and DOS supported by FINAL CUT?](https://github.com/gansm/finalcut/wiki/Frequently-Asked-Questions#are-windows-and-dos-supported-by-final-cut)

It is not necessary to "own" it if you grab the "Community Edition" so native windows console should be an option.

**Comment by gansm** [comment]
Hi Ryder17z,

Please excuse me if I left room for speculation about a Windows port by myself in my last reply. I wanted to express that I have been using Linux and various Unix derivatives exclusively since 1996. I have only tinkered with Microsoft Windows sporadically. As a result, I do not have sufficient knowledge of Windows systems programming to create a class derived from FOutput for the Windows operating system.

However, if you have the necessary expertise and are willing to help, I would greatly appreciate it if you could create a FOutput-derived class for the Windows OS to make FINAL CUT run on Windows. Your help would be of great value to me and my work.

Thank you for taking the time to consider my request, and I look forward to hearing from you.

**Comment by Ryder17z** [comment]
Unfortunately I don't feel qualified for this. I just thought I'd let you
know how it's been for the last 6+ years. I'm just a hobbyist coder.
