### ISSUE TITLE
Example applications freeze when you press enter instead of using mouse

### ISSUE THREAD

**Issue by lighth7015** [gansm/finalcut#88]
## Describe the bug

Example applications freeze when you press enter instead of using mouse

## How to reproduce the bug?

Run any of the included example applications, and activate the `exit` button/dialog with the enter key instead of the mouse, and the application will stop responding.

## What behavior did you expect?

The application exits as expected.

## In which environment did the bug occur?
* Which operating system do you use?
  Linux

* Which distribution do you use?
  Manjaro Linux

* On which CPU architecture did you test?
  x86_64, AMD Ryzen 7 1700

* Which compiler/version did you use?
  both clang++ 12.0.1 and GCC 11.1.0

* Which terminal do you use?
  konsole

* What does the environment variable $TERM contain?
  `xterm-256color`

**Comment by gansm** [comment]
Unfortunately, I cannot reproduce your problem here in a virtual machine.

**1. I start the hello application**
![grafik](https://user-images.githubusercontent.com/12223838/136015477-217e585d-c53a-4ed4-81ca-a27fe1e1811c.png)

**2. I try to exit the application with &lt;o&gt;, &lt;spacebar&gt; or &lt;enter&gt;**
![grafik](https://user-images.githubusercontent.com/12223838/136015505-8f0166c5-da67-4bc1-b6d3-5fcf0cdad04a.png)

**3. The application has been exited properly**
![grafik](https://user-images.githubusercontent.com/12223838/136015553-55eac453-dce6-433b-928c-c5f0dee54f29.png)

Tested with my last commit (875614a).


_PS: Konsole in one of the weakest terminal emulators. It still does not support the redefinition of existing colors [source](https://lists.gnu.org/archive/html/bug-ncurses/2014-03/msg00019.html). I can recommend all [VTE](https://github.com/GNOME/vte) based terminal emulators like [LXTerminal](https://github.com/lxde/lxterminal)._

**Comment by gansm** [comment]
Is `examples/keyboard` working for you?

**Comment by gansm** [comment]
@lighth7015:
Do you still have this problem?

**Comment by lighth7015** [comment]
I'll test it again and let you know. I've been busy at work, sorry!

**Comment by lighth7015** [comment]
Okay it seems to have been an issue with my terminal, thanks!

**Comment by gansm** [comment]
Thank you for testing
